Nix-Security-WG/nix-security-tracker

- .gitignore
- README.md
- exe/Main.hs
- flake.lock
- flake.nix
- scan.sh
- src/CVENix/Examples.hs
- src/CVENix/SBOM.hs
> Parse SBOM

- CVENix.cabal
- exe/Main.hs
- src/CVENix/CVE.hs
- src/CVENix/Examples.hs
- src/CVENix/Matching.hs
- src/CVENix/SBOM.hs
- src/CVENix/Utils.hs
Clearly I seem to have done something wrong here, as it now appears to parse the CVE list twice. Can you spot my mistake?
> Refactor matching to its own file

- src/website/shared/management/commands/ingest_bulk_cve.py
this was accidentally destroyed in f3e55b407ef068d13cf1d233566231d9c21a875c
@alejandrosame @tom-hubrecht
> fix: bring back `--test` flag on the ingestion command

- src/website/shared/management/commands/ingest_manual_evaluation.py
> fix: missing rename

- default.nix
- nix/overlay.nix
- pkgs/default.nix
- pkgs/python/default.nix
- pkgs/python/django-ninja/default.nix
- pkgs/python/pyngo/default.nix
the overlay packages did not end up in the final package set. now they are.
@alejandrosame
> fix: make overlay work as intended

- src/website/webview/admin.py
> add more admin convenience

- README.md
- default.nix
the schema now uses postgres-specific types.
>  docs: switch from sqlite to postgresql 

- nix/overlay.nix
- pkgs/python/django-pgpubsub/default.nix
- pkgs/python/django-pgtrigger/default.nix
- src/website/tracker/settings.py
This provides a solid base for background tasks.
> Background tasks

- default.nix
- nix/tests/utils.nix
- nix/tests/vm-basic.nix
- nix/web-security-tracker.nix
- npins/default.nix
- pkgs/python/django-pgpubsub/default.nix
- pkgs/python/django-pgtrigger/default.nix
- staging/configuration.nix
- staging/hardware-configuration.nix
- staging/kurisu-proxy.nix
- staging/sectracker.nix
before introducing noise in every commit, let's settle this once.
this was made necessary by #87, sorry.
> style: apply nixfmt globally

- nix/overlay.nix
- src/website/shared/urls.py
- src/website/shared/views.py
- src/website/tracker/settings.py
- src/website/tracker/urls.py
> feat: list issues and filter by referenced CVEs in REST API

- exe/Main.hs
- src/CVENix/Matching.hs
- src/CVENix/NVD.hs
- src/CVENix/Types.hs
- src/CVENix/Utils.hs
- src/CVENix/WebData.hs
Seems to invoke the webservice fine.
TODO:
* add a flag to specify the online tracker URI, or to skip the network call entirely
* test with actual data that the result is correct
* by default don't output advisories that have a nixpkgs issue in `notforus` state or similar
> Invoking the ws

- README.md
- nix/tests/utils.nix
- nix/web-security-tracker.nix
now we can also test static files being served
> feat: test nginx reverse proxy as well

- .gitignore
- src/website/shared/git.py
- src/website/shared/management/commands/initiate_checkout.py
- src/website/tracker/settings.py
breakdown of #123
Does a few renamings and fixes missing type annotations to appease the linter
> add code for managing a Nixpkgs checkout

- .gitignore
- README.md
- contrib/get-all-hydra-jobs.sh
- contrib/reset.sh
- default.nix
- src/website/shared/management/commands/fetch_all_channels.py
- staging/deploy.sh
this also removes the hard-coded Nixpkgs checkout for evaluations
> docs: update onboarding and handling instructions

- flake.lock
- src/LocalSecurityScanner/Matching.hs
Initial implementation of #75 . We may still want to parse the derivation ourselves as well eventually.
Fixes #76, #78 and #151.
> feat: take into account patch information from sbom

- nix/web-security-tracker.nix
`fetch-all-channels` uses Git underneath, make sure it's available.
> fix: add `git` to service environment

- .gitignore
- default.nix
- nix/web-security-tracker.nix
- src/website/shared/management/commands/ingest_bulk_cve.py
- src/website/tracker/settings.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/153
> fix: ensure CVE cache directory always exists

- nix/tests/utils.nix
- nix/web-security-tracker.nix
otherwise a failed service will restart a number of times until the test ends
> test: fail fast

- default.nix
on popular request by flake-using @Erictapen :)
> feat: allow parameterising `system` at the top level

- default.nix
the diff looks huge, but semantically this is a tiny change:
add `lib` to the top-level arguments and don't merge tests separately
since they're already part of the `rec` attrset.
> refactor: simplify default.nix attrset

- nix/dev-setup.nix
It doesn't seem that PostGIS is required for this project (yet)?
> fix(build): drop postgis as it seems unneeded in the codebase

- nix/web-security-tracker.nix
Make some of the required programs be available in the environment.
> feat(module): fix wst-manage script

- staging/deploy.sh
which is not available in the CI environment.
> fix(ops/staging): use the git root instead of $DIRENV_FILE

- staging/deploy.sh
So that everywhere there's Nix, this *WORKS*, period.
> fix(ops/staging): use a nix-shell shebang

- .github/workflows/deploy.yaml
- staging/staging_host_keys
We put them in the repo to be able to update them easily.
> fix(cd): trust staging server SSH keys

- src/website/shared/management/commands/ingest_delta_cve.py
Fixes #228.
This fetches everything from [last ingestion day + 1, date] (notice the bracket to mean included/excluded precisely).
In another way, fetches everything in ]last ingestion day, date].
> feat(mgmt/delta-cve): ingestion of delta catch up based on the next ingestion day

- CONTRIBUTING.md
- contrib/mkcredentials.sh
Also I wrote down how to create a `SECRET_KEY` for Django.
One thing left for me is to customise the `GH_ORGANIZATION` easily.
> docs: improve GitHub setup for local development

- src/website/shared/management/commands/ingest_delta_cve.py
This was the wrong call, we were raising CommandError(s).
> fix: make the delta code report no releases rather than UO exceptions

- .github/workflows/database-dumps.yaml
- staging/dump-database.sh
This will help us to understand which credentials are set.
Signed-off-by: Raito Bezarius <masterancpp@gmail.com>
> chore(ci): debug credentials in CI

- .gitignore
- CONTRIBUTING.md
- default.nix
this will bite you if you don't do it
> docs: show how to set GitHub parameters

- src/website/shared/models/nix_evaluation.py
- src/website/webview/static/style.css
- src/website/webview/templates/suggestion_list.html
- src/website/webview/views.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/203
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/210
Some better rendering for package versions.
> feat: Suggestion view pt.2

- src/website/webview/static/style.css
- src/website/webview/templates/suggestion_list.html
Very quick layout for the buttons themselfes, that doesn't do anything yet.
Addresses, but not closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/206 and https://github.com/Nix-Security-WG/nix-security-tracker/issues/207.
> feat: add buttons to add another package, dismiss and create a draft

- src/website/webview/views.py
- staging/s3-revproxy/default.nix
Signed-off-by: Raito Bezarius <masterancpp@gmail.com>
> misc: buffering for s3-revproxy and faster queries for suggestions view

- src/website/shared/templates/base.html
- src/website/webview/static/style.css
- src/website/webview/templates/suggestion_list.html
- src/website/webview/views.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/291
> feat: provide basic pagination in suggestions view

- src/website/webview/static/style.css
- src/website/webview/templates/suggestion_list.html
- src/website/webview/views.py
very hastily done
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/206
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/207
> feat: actually change suggestion state in suggestions view

- CONTRIBUTING.md
Until https://github.com/Nix-Security-WG/nix-security-tracker/issues/198 is fixed
> docs: how to copy staging db to local development server

- src/website/shared/models/nix_evaluation.py
- src/website/webview/static/style.css
- src/website/webview/templates/components/nixpkgs_package.html
- src/website/webview/templates/components/nixpkgs_package_list.html
- src/website/webview/templates/components/selectable_nixpkgs_package_list.html
- src/website/webview/templates/draft_list.html
- src/website/webview/templates/suggestion_list.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/323
Needed some refactoring, so we don't show the checkbox in the other views
There is lots more to do, but this should provide basic functionality.
> feat: allow for package deselection on the suggestions view

- .github/workflows/bump.yaml
Closes #357
Based on the instructions from https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
> ci: Use token from GitHub app to trigger checks

- src/website/webview/static/style.css
I just couldn't not do it :see_no_evil:
> fix: proper ellipsis in suggestions

- src/website/webview/static/style.css
- src/website/webview/templates/dismissed_list.html
- src/website/webview/templates/selected_list.html
- src/website/webview/templates/suggestion_list.html
No time at all was spent on finding the colors here, so feel free to change in the future. This is only about consistency
> feat: introduce a basic color palette for suggestion, dismissed, selected and draft

- src/website/webview/static/style.css
- src/website/webview/templatetags/viewutils.py
> feat: actually display severity (only low, high for now)

- src/website/shared/listeners/cache_suggestions.py
Closes #294 
Before that, `2024-11-27` as a version would have been rendered as `27`.
> fix: correct derivation name parsing for pname/version pairs

- staging/dump-database.sh
This is not testing the right thing, let's remove it.
> fix(staging/dump-database): do not exit for wrong reasons

- staging/dump-database.sh
The GC requires to be passed the endpoint URL as well.
> fix(staging/dump-database): fix the GC

- src/website/webview/templates/components/suggestion.html
- src/website/webview/templates/components/suggestion_activity_log.html
- src/website/webview/templates/components/suggestion_state_changed.html
- src/website/webview/templates/suggestion_list.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
also refactored update_suggestion, this method was never meant to only be called once
Fixes #421
> fix: undo action didn't work anymore

- src/website/shared/templates/base.html
- src/website/webview/static/style.css
- src/website/webview/templates/components/selectable_nixpkgs_package_list.html
- src/website/webview/templates/components/suggestion.html
- src/website/webview/views.py
Depends on #422 as I refactored some stuff there.
Closes #411
> feat: instant package removal

- src/website/webview/views.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/356
> feat(suggestions): order by update timestamp

- src/website/webview/static/style.css
- src/website/webview/templates/components/suggestion.html
- src/website/webview/templates/components/suggestion_activity_log.html
- src/website/webview/templates/suggestion_list.html
- src/website/webview/urls.py
Follow-up to #430 
I choose "drafted" in the activity log, even though I'm not sure how good of a fit it is. "To draft a letter" is a thing though.
> fix: rename /selected to /drafts

- pyrightconfig.json
- src/website/shared/listeners/cache_suggestions.py
- src/website/webview/static/style.css
- src/website/webview/templates/components/maintainers_list.html
- src/website/webview/templates/components/suggestion.html
- src/website/webview/templatetags/viewutils.py
> feat: show package maintainers that are going to be pinged

- src/website/shared/templates/base.html
- src/website/webview/static/style.css
> feat: show username of logged in user in navbar

- src/website/shared/logs/logs.py
> feat(suggestions): fold repeated packages updates

- src/website/webview/static/style.css
This is not really a decision about color values, more one about using the same variables everywhere so we have an easier time adapting the palette.
> fix: make css color values more consistent

- src/website/shared/templates/base.html
- src/website/webview/static/style.css
- src/website/webview/templates/components/pagination.html
- src/website/webview/templates/suggestion_list.html
and generally use more classes for styling
the overall change looks a bit messy but it's actually a simplification (trust me I'm an artist)
> fix: unbreak pagination list

- src/website/webview/static/style.css
- src/website/webview/templates/home_view.html
> feat: show overview on frontpage

- nix/web-security-tracker.nix
This change has to be validated with the application of the revert https://github.com/Nix-Security-WG/nix-security-tracker/pull/402
> feat: configure teams through settings for deployment

- src/website/tracker/settings.py
- staging/sectracker.nix
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/399. Towards https://github.com/Nix-Security-WG/nix-security-tracker/issues/138
> feat: configure repository to post issues to

- src/website/shared/logs/logs.py
- src/website/webview/templates/components/suggestion_activity_log.html
- src/website/webview/templatetags/viewutils.py
> feat(suggestions): format tracked package names like in package list below

- src/website/webview/templates/components/selectable_nixpkgs_package_list.html
- src/website/webview/templates/components/suggestion.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/324
> feat(suggestions): auth checks for update actions

- src/website/webview/templatetags/viewutils.py
Originally, I had the guard with @login_required decorator. That was giving problems and the check got lost with some refactors.
> fix(suggestions): add missing anonymous check

- src/website/webview/templates/issue_list.html
> feat: show issue pipeline on /issues

- src/website/webview/templates/components/selectable_nixpkgs_package_list.html
- src/website/webview/templates/components/suggestion.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
Reapply the auth check commits and add logic changes to make them work as intended.
> Fix suggestion undo and auth check integration

- .github/workflows/builds.yaml
> test: run VM tests in CI

- src/website/shared/models/cached.py
- src/website/shared/models/linkage.py
- src/website/tracker/settings.py
ytf does ruff suddenly find new things to complain about
> more formatting fixes

- src/website/shared/github.py
Follow-up of #516 (opening a Github issue). When publishing an issue, this PR adds the information of affected Nix packages together with their version and the channel as collapsable section at the end of the issue description. Here is an example of such a generated issue: https://github.com/nix-sec-tracker-test/nixpkgs/issues/35
> feat: add affected packages to Github issue

- default.nix
- infra/sectracker.nix
- nix/tests.nix
- src/website/tracker/settings.py
this makes them required and safe for all environments
> refactor: add types to settings related to GitHub

- src/website/shared/tests/test_github_sync.py
this merely changes a few readability things as a vehicle for me to get more familiar with the code
> educational refactoring of the GitHub sync tests

- infra/configuration.nix
Part of #222, opening as draft until I figure out if there are more metrics we can easily add.
> infra: Expose nix and cve metrics from postgres

- CONTRIBUTING.md
- nix/tests.nix
- src/website/shared/github.py
- src/website/tracker/settings.py
this is a preliminary to test the UI side of the login workflow, which still
requires a few simplifications to separate the moving parts.
> simplify wiring of secrets and GitHub authentication
