- CVENix.cabal
- src/CVENix/Examples.hs
- src/CVENix/Matching.hs
Now produces a result like:
```
Matched advisories:
"avahi"	"/nix/store/08xh2gdj9ji94fcjpf2hpz42jim99kkp-avahi-0.8.drv"	"CVE-2023-38473"
"gawk"	"/nix/store/jzc31i1d1mi6x2rmp9pj6dcvw2mx7daz-gawk-5.2.2.drv"	"CVE-2023-4156"
"glib"	"/nix/store/09yqd7yg7rfjsfbikvc3snx7wn9c6is5-glib-2.76.4.drv"	"CVE-2023-29499"
"glibc"	"/nix/store/30j4y2k04zww68mggx1mkmmi6b9ns2yp-glibc-2.38-27.drv"	"CVE-2023-5156"
"glibc"	"/nix/store/3affpfhnsgifgqkhd1zckk527a86fyrz-glibc-locales-2.38-27.drv"	"CVE-2023-5156"
"kernel"	"/nix/store/h3sqgjbm7a3gvyn50r5k7066xjhgn5iy-kernel-modules.drv"	"CVE-2023-6176"
"libX11"	"/nix/store/wxd38000dmzrd51nl4d0q88c3xximhlr-libX11-1.8.7.drv"	"CVE-2023-43787"
"libXpm"	"/nix/store/a66y6hxcv8qcal43i49nvrzfi7k9jj12-libXpm-3.5.17.drv"	"CVE-2023-43789"
"libtiff" …
```
> Print advisory matches

- README.md
to make sure people will be testing the right version
> add `cabal install --overwrite-policy=always` to readme

- src/website/shared/management/commands/ingest_manual_evaluation.py
On insertion, the function `set_m2m` was getting the relationiships for the same class collapsed into a `None` key. This caused m2m relationships to get lost during the processing.
With this fix, the logic can again retrieve the proper foreign keys from the `self.m2m_models` list.
For example, now each `nixderivationmeta` gets correctly linked to its corresponding `nixderivationmeta_maintainers`. This can be checked after ingestion by running the query `SELECT * FROM shared_nixderivationmeta_maintainers;`.
> fix: m2m relationships on insertion

- README.md
- src/website/shared/fixtures/sample.json
Add a fixture file for the `shared` app to use during development. It contains a subset of ~100 CVEs and ~100 evaluation entries.
The README has been updated to include instructions on how to load and recreate the fixture file.
> feat: add fixture for quick dev data setup

- contrib/get-all-hydra-jobs.sh
otherwise we won't get any of the vulnerable packages to display
> fix: evaluate insecure packages as well

- .gitignore
- default.nix
- nix/overlay.nix
- src/website/shared/management/commands/ingest_bulk_cve.py
Most of the time spent on CVE import is fetching and uncompressing the CVE bundle from Github. This penalizes development work on the database, where multiple reimports might be needed.
Now the CVE data gets stored in a local cache directory after the first fetch. It's still possible to force the deletion of the CVE cache to download the bundle again with the `--force-download` option.
> feat: keep CVE data in a local cache directory for efficient reimports

- default.nix
- pyproject.toml
- src/website/shared/fetchers.py
- src/website/shared/management/commands/ingest_bulk_cve.py
- src/website/shared/management/commands/ingest_delta_cve.py
- src/website/shared/management/commands/ingest_manual_evaluation.py
Life is too short to debate about naming conventions. Let's just use something that is widely accepted and move on.
JSONWizard will automatically convert from camelCase:
```
from dataclasses import dataclass
from dataclass_wizard import JSONWizard
@dataclass
class MaintainerAttribute(JSONWizard):
name: str
github: str | None = None
github_id: int | None = None
email: str | None = None
matrix: str | None = None
def main() -> None:
m = MaintainerAttribute.from_json("""
{
"name": "John Doe",
"github": "johndoe",
"githubId": 123456,
"email": "john@doe.info",
"matrix": "johndoe%example.com"
}
""")
print(m.github_id) # 123456
if __name__ == "__main__":
main()
```
> build: enable naming convention linter

- pyproject.toml
- src/website/manage.py
- src/website/shared/fetchers.py
- src/website/shared/management/commands/ingest_bulk_cve.py
- src/website/shared/management/commands/ingest_delta_cve.py
- src/website/shared/management/commands/ingest_manual_evaluation.py
- src/website/shared/management/commands/register_channel.py
- src/website/shared/models/cve.py
- src/website/shared/models/nix_evaluation.py
- src/website/shared/utils.py
- src/website/webview/views.py
This is very recommended for large code bases and mixed teams. It can replace integration tests in some places. I used Any in a few places here. However note that this is still better than using no type because it will than type check this function as well.
Depends on https://github.com/Nix-Security-WG/nix-security-tracker/pull/103
> build: enforce type annotations

- .reuse/dep5
- CHANGELOG.md
- CONTRIBUTING.md
- LICENSES/CC0-1.0.txt
- LICENSES/MIT.txt
- LocalSecurityScanner.cabal
- README.md
- exe/Main.hs
- flake.nix
- src/LocalSecurityScanner/CVE.hs
- src/LocalSecurityScanner/Examples.hs
- src/LocalSecurityScanner/Matching.hs
- src/LocalSecurityScanner/NVD.hs
- src/LocalSecurityScanner/SBOM.hs
- src/LocalSecurityScanner/Types.hs
- src/LocalSecurityScanner/Utils.hs
- src/LocalSecurityScanner/WebData.hs
- tests/Main.hs
So it now passes 'reuse lint' (https://reuse.software)
> Add license metadata

- src/website/shared/git.py
the error message doesn't matter since we only care about the return
code. but it's confusing (and will probaby spam logs) when it appears,
since it looks like there's something wrong while everything is alright.
> fix: swallow stderr on `git cat-files`

- contrib/reset.sh
- default.nix
- src/website/shared/management/commands/ingest_manual_evaluation.py
I decided to reset the dev environment and ran into issues with the default setup. This PR solves the inconsistencies found so that `./contrib/reset.sh` works again.
Ideally, we should converge the behaviour of the ingestion through the listener and the manual ingestion so it's clear how to do it as a one-shot operation.
> fix: update reset script commands

- src/website/shared/templates/base.html
- src/website/webview/templates/affected_list.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/urls.py
- src/website/webview/views.py
Create a simple tabbed view for those derivations that appear in an issue marked as 'affected'.
The styles broke in weird ways when moved to the main `style.css`, so I leave them in the template document for the time being.
> feat: add view for affected packages per channel

- nix/web-security-tracker.nix
removing constraints on the Host header in development mode allows
serving requests from the local network
> feat: allow deployment on local network

- nix/web-security-tracker.nix
for everything else it will error on CHDIR, even if $PWD has the right
owner and permissions.
> fix: run wst-manage in service directory

- default.nix
this way one can deploy the service as a container and rest assured that
it will work. otherwise there will almost certainly be conflicts with
the host system's Nixpkgs version.
Example:
```nix
{ config, ... }:
let
sectracker = import ~/src/nix-security-tracker { };
in
{
containers.nix-security-tracker = {
config = { ... }: {
nixpkgs = {
inherit (sectracker) pkgs overlays;
};
imports = [
sectracker.module
];
};
};
}
```
> feat: export packages

- default.nix
For my local setup, to be able to use `psql` in the shell.
> refactor: move env vars in shell into env, allow for using psql

- .github/workflows/deploy.yaml
Otherwise, it's hard to deploy anything.
> fix(cd): install a `nixpkgs` channel

- CONTRIBUTING.md
- nix/overlay.nix
- src/website/tracker/settings.py
- staging/secrets.nix
- staging/secrets/glitchtip-dsn.age
- staging/sectracker.nix
Via Sentry SDK, we configure a GLITCHTIP_DSN as provided by GlitchTip.
One per environment.
Depends on #261.
Fixes #229.
> feat: support GlitchTip integration

- src/website/shared/utils.py
- staging/secrets.nix
- staging/secrets/gh-app-installation-id.age
- staging/sectracker.nix
It's not sufficient to just obtain a JWT, it's also required to use an installation ID to access things from the org attached to the installation ID.
> fix(github): use AppAuth with an installation ID

- staging/s3-revproxy/default.nix
This caused the Go segfault in production as I didn't pass any bucket information per target.
> fix(staging): oopsie, forgot to pass the bucket information

- .github/workflows/database-dumps.yaml
Now, it can be manual and it has concurrency protection.
> chore(gha): improve the dump system

- staging/dump-database.sh
They are already set in my local environment, but not here, which made it fail.
Self-merging, it's a trivial fix.
> fix(staging/dump): add missing environment variables

- staging/s3-revproxy/default.nix
Previously, we were mounting the bucket in the wrong location.
> fix(staging/s3-revproxy): fix Host mounting

- nix/web-security-tracker.nix
- staging/container.nix
since migrations may be quite expensive when the datase state diverges
enough, the container will get killed before it's ready even if
everything is alright. the logs are quite opaque in that case,
because, well, there's no failure.
> fix: increase timeout on the container

- default.nix
credentials are currently required to run the service at all, and the
docs show how to set things up.
> chore: don't auto-create dummy credentials

- src/website/webview/static/style.css
This led to janky behaviour, this one takes a bit more space but is easier to reason about.
Also introduce flex on the list of packages, so that we can use row-gap
> style: don't use flex in package element

- src/website/shared/templates/base.html
- src/website/webview/static/style.css
Afair we don't really track wether the software runs as staging. I figured just determining wether it's running in debug mode would be enough as a heuristic.
Closes https://github.com/Nix-Security-WG/nix-security-tracker/issues/279
> feat: display a security disclaimer when being run in debug mode to warn staging users

- .github/workflows/builds.yaml
- .github/workflows/database-dumps.yaml
- .github/workflows/deployments.yaml
- .github/workflows/dry-activations.yaml
- default.nix
- staging/deploy.sh
- staging/dump-database.sh
this doesn't rely on NIX_PATH and is therefore fully pure, and uses our
own, controlled dependencies.
the Nixpkgs for deployment currently not decoupled from the one for
development because the build is broken on the newest version.
we still need a policy for how to run updates, but ideally we'd use
exactly one version of Nixpkgs for everything.
> ci: pin Nixpkgs for deployments

- src/website/webview/static/style.css
Apparently https://github.com/Nix-Security-WG/nix-security-tracker/pull/304 didn't exactly do what I intended, no idea how that screenshot in https://github.com/Nix-Security-WG/nix-security-tracker/pull/304#issuecomment-2450565850 came together.
> fix: display for channel summaries

- .github/workflows/builds.yaml
- .github/workflows/bump.yaml
- .github/workflows/trigger.yaml
- default.nix
we can extend this easily to also update the development pins. I suggest we keep them in sync, so there's no room for divergence, because breaking builds will hold up everything anyway, so we may just fix them for all outputs at once.
> ci: auto-update pins for staging

- src/website/webview/static/style.css
- src/website/webview/templates/components/suggestion_state_button.html
- src/website/webview/templates/dismissed_list.html
- src/website/webview/templates/draft_list.html
- src/website/webview/templates/suggestion_list.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
previously if changing a suggestion state, one would get redirected to
the first page.
this also removes the templatetag for the buttons, as it adds an extra
interface that doesn't make the overall code shorter.
> fix: return to same page after change state

- src/website/shared/models/nix_evaluation.py
- src/website/webview/static/style.css
- src/website/webview/templates/components/nixpkgs_package_list.html
Old code that I should have pushed long ago.
Addresses https://github.com/Nix-Security-WG/nix-security-tracker/issues/333 but doesn't close it yet, as it is blocked by #338.
I needed to introduce the flexbox again, but I think it is fine, as the versions block has a fixed width? Shouldn't be too hard to make it look right.
This change is invisible actually, as there is no data to display yet.
> feat: display meta.description for package in suggestion list

- src/website/shared/evaluation.py
This was disabled for performance reasons (probably?!), re-enabled.
This was tested to work locally.
Fixes #338.
> fix(evaluation): link metadata to derivations

- src/website/webview/static/style.css
An idea I just had because I felt the fact the the package is (about to) removed isn't clear enough yet.
> feat: signify a package to be removed by crossing through its name

- src/website/webview/static/style.css
Just makes it a little bit better on desktop, still shit on small screens.
> fix: overflow on version names

- src/website/shared/apps.py
Autoreloader restarts the child process with `RUN_MAIN` as an environment variable.
This is undocumented but can be known by reading Django source code.
Fixes #285.
> feat(shared/apps): do not reload the github state via autoreloader

- src/website/webview/static/style.css
Closes #333 
Good enough, will be refined with #209 anyways.
> fix: render package description in a better way

- nix/web-security-tracker.nix
- src/website/shared/apps.py
We just create a bespoke environment variable set by our packaging.
There's no other way as we cannot depend on any specific WSGI/ASGI
server argv0 here.
Fixes #239.
Depends on #392.
> feat(shared/apps): run github sync state in production

- .github/workflows/database-dumps.yaml
By default, GitHub won't load them if I don't ask for them.
Should fix #198.
> fix(ci/dumps): pass explicitly the required secrets

- nix/web-security-tracker.nix
- src/website/shared/fetchers.py
- src/website/shared/management/commands/ingest_delta_cve.py
It supports parallelism but `make_cve` does not.
This will result in many deadlocks and issues during the transaction if
it's run with more than one process.
Signed-off-by: Raito Bezarius <masterancpp@gmail.com>
> feat: the delta CVE ingester can replace the bulk CVE ingester

- nix/web-security-tracker.nix
- src/website/shared/management/commands/crash_all_evaluations.py
- src/website/shared/models/nix_evaluation.py
This way, it's not possible to have leftovers not taken care until the next worker restart.
Now, "pending" evaluations can happen only in-between two worker restarts.
For this, we can add a supervisor timer unit that will check if there's any evaluation taking far too long (> 24 hours) and will forcibly restart the worker.
With that, the loop is closed.
Counts towards #390.
> fix(evaluation): crash pending evaluations at worker restart

- Procfile
- nix/web-security-tracker.nix
This ensures that at restart, locked notifications that did not terminate are resumed.
Count towards #390.
> fix(staging/worker): apply automatic recovery for locked notifications

- src/website/shared/listeners/cache_suggestions.py
- src/website/shared/models/cached.py
- src/website/shared/models/linkage.py
- src/website/webview/views.py
Couldn't sleep with having this problem in my head.
I had to switch the arguments for the update_or_create function because they were wrong: The proposal_id is used for the lookup and the payload is then used on update.
This is going to make updates very slow, but doesn't affect page load and I'd argue that it is important to have correct behaviour at first. With https://github.com/Nix-Security-WG/nix-security-tracker/pull/383 merged update times wouldn't even be noticable.
> fix: refresh suggestion cache entry on derivations update

- src/website/shared/logs/logs.py
- src/website/webview/templates/components/suggestion_activity_log.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
Closes #427
Some local benchmark comments:
- From main, before refactor, running the queries in the selected page gave me: + CPU 3124ms DOMloading 4.23s.
- After changing the query to a union an on db aggregation:
+ CPU 322ms DOM 638ms
- After bulk filtering in the query (that is, adding pgh_obj_id__in filtering): + CPU 409ms DOM 831ms
- After adding final dictionary aggregation:
+ CPU 308ms DOM 802ms
Therefore, with more data in the future, it can be reconsidered whether the bulk grouping is offering a good speedup tradeoff over filtering by single suggestion IDs.
The biggest speedup in this refactor was achieved by eliminating data roundtrips by using union and subqueries in the activity log fetch.
> refactor(suggestions-log): implement as on db bulk aggregation query

- src/website/shared/management/commands/ingest_delta_cve.py
This explains why we were never catching up, we were always restarting from scratch.
> fix: ingest newest CVEs, not oldest CVEs

- nix/web-security-tracker.nix
According to the [documentation](https://docs.allauth.org/en/dev/account/configuration.html) of django-allauth, `ACCOUNT_DEFAULT_HTTP_PROTOCOL` should be set to `https` in order to generate authentication links using https instead of http. This is currently needed in order to generate the correct callback URL for GitHub.
> fix: Generate links with https when in production

- src/website/webview/templates/components/maintainers_list.html
> fix: don't show maintainers email when it is none

- src/website/shared/listeners/cache_suggestions.py
- src/website/webview/static/style.css
- src/website/webview/templates/components/nixpkgs_package.html
Closes #440 
~~The code should be robust for e.g. `nixpkgs-darwin-24.11` and `nixos-24.11-small` to have different revisisions, though I never see any difference between these. Probably just because they evaluation did actually happen on the same commits?~~
> feat: display src file location next to the version for each derivation

- src/website/webview/static/style.css
- src/website/webview/templates/components/suggestion_activity_log.html
This is a bandaid, a nicer solution would be to fold pairs of state changes into nothing, if they are only a few minutes apart and nothing else happened inbetween.
Fixes #455
> fix: render state changes back to automatic suggestion in the activity log

- nix/web-security-tracker.nix
- src/website/shared/apps.py
Reverts Nix-Security-WG/nix-security-tracker#401
Depends on https://github.com/Nix-Security-WG/nix-security-tracker/issues/398
> Revert "Revert "feat(shared/apps): run github sync state in production""

- nix/web-security-tracker.nix
- staging/sectracker.nix
The defaults live in tracker/settings.py, which should be overridden through the deployment configuration file.
> fix: move teams configuration to staging deployment

- src/website/shared/templates/base.html
It is supposed to be removed once we can guarantee that we won't need to wipe the database later.
I just thought this would be important to have now to manage the expactions of those currently trying out the deployment on tracker.security.nixos.org.
Closes #472
> feat: display a disclaimer on production

- src/website/webview/views.py
Return an empty list as there might not be an activity log and this will result in a key error and an HTTP 500 returned to the user.
> fix: Fix a bug in POST requests to suggestions

- README.md
It took me some time to find out that there was a deployed tracker, because it's in the _about_ section of the project, which I personally almost never read or notice. This PR adds the link to the deployed tracker to the README, which is usually the first thing you read when arriving on the repo page (as a bonus, people cloning the repo without using the GitHub interface will also get the link now).
> Add link to the deployed tracker to the README

- infra/README.md
- infra/configuration.nix
Related to #345, this PR adds two prometheus exporters to the deployment, one for generic postgres metrics and one to run custom queries. The custom queries exposed currently are:
1) Number of registered users
2) Unix timestamp since the last matching
3) Unix timestamp since the last delta
> infra: Export Postgres and SQL metrics

- src/website/shared/models/cached.py
Split from #498. Add a property to a cached suggestions that retrieve all the maintainers from all the affected packages, deduplicated by GitHub ID. This will be used to ping maintainers in the final GitHub issue.
> feat: add all_maintainers() property to cached suggestions

- src/website/webview/static/style.css
Split off from #498. This adds CSS classes for the coming published status (see #511, although the two are technically independent).
> feat: add CSS classes for published status

- src/website/shared/models/linkage.py
Split off from #498. Add a helper to suggestions (`CVEDerivationClusterProposal`) to create a new `NixpkgsIssue` object from its data. This is supposed to be the main way of creating new `NixpkgsIssue` in the final workflow: when clicking on "Publish Issue" for an accepted issue, a `NixpkgsIssue` will be created using this method, the status will be set to published and an actual GitHub issue will be opened on Nixpkgs.
> feat: add create_nixpkgs_issue() to suggestions

- src/website/tracker/settings.py
Split from #498: preliminary work adding a setting to escape maintainers' names when creating a GitHub issue to avoid pinging them while the feature isn't yet well tested.
> refactor: add GH_ISSUES_PING_MAINTAINERS setting

- .github/workflows/bump.yaml
- .github/workflows/deployments.yaml
- .github/workflows/dry-activations.yaml
it doesn't seem to be of use any more since the GitHub cache API was disabled
> ci: drop magic-nix-cache-action

- src/website/shared/github.py
Split off from #498. This PR adds an endpoint to the `github` module to create and publish a GitHub issue on the Nixpkgs repository (actually the one configured in `settings`) from an accepted suggestion.
> feat: add create_gh_issue() helper

- src/website/webview/templates/components/suggestion.html
- src/website/webview/templates/components/suggestion_state_changed.html
- src/website/webview/views.py
This is the last chunk of #498, which adds the "Publish issue" button and implements its behavior in the backend. Includes and supersedes #516.
> feat: re-enable "Publish issue" button

- src/website/webview/static/style.css
- src/website/webview/templates/components/suggestion_state_error.html
- src/website/webview/templates/components/suggestion_state_error_wrapper.html
- src/website/webview/views.py
Follow-up of #516. This PR adds a small component, similar to the one handling state changes, to report errors during suggestion state transitions. More specifically here, the potentially fallible transition is to publish a GitHub issue, as this implies an external call to the GitHub API. In that case, if any step of the publication fails, the component will show that an error has occurred:
> feat: add status change error component

- CONTRIBUTING.md
- src/website/shared/github.py
- src/website/tracker/settings.py
- src/website/webview/views.py
Closes #501. The code looks fine but I have a permission issue to solve to properly test it; labels are just ignored currently, but if I try to add them manually on the created issue with `add_to_labels`, I get a proper 403, so something needs to be done (and documented) around GitHub access rights/PATs.
> feat: attach labels to github issue

- .github/codeql/codeql-config.yaml
- .github/workflows/codeql.yaml
I am experimenting with GitHub's [CodeQL](https://codeql.github.com/) static analyzer and this project is a good target, because it manipulates user input (in URLs).
Look at the vulnerabilities found on my fork: https://github.com/smelc/nix-security-tracker/security/code-scanning IMHO most of the reports are good:
By default this check is non intrusive, because this new pipeline only blocks merging when a new _error_, _critical_, or _high_ severity is found in code changed by the PR (see [corresponding doc](https://docs.github.com/en/enterprise-server@3.13/code-security/code-scanning/managing-code-scanning-alerts/triaging-code-scanning-alerts-in-pull-requests#code-scanning-results-check-failures)). As visible in the image above, all existing alerts are below this treshold.
If we want the …
> CI: run CodeQL

- src/website/shared/templates/account/logout.html
- src/website/shared/templates/socialaccount/login.html
towards #544
this primarily removes dangling references to CSS classes and
superfluous elements.
also we currently dont' support the "connect" workflow. the relevant parts
can be added back when we have a proper user story for that.
> style: simplify login/logout templates

- src/website/tracker/settings.py
towards #464
this is a bit more than merely a refactoring: now you can override the
entire configuration from outside (e.g. using Nix attrsets) without
touching secret values.
also the type declaration allows inferring the shape of allowed values
without having to check allauth documentation.
> refactor: structured configuration for allauth

- default.nix
- nix/web-security-tracker.nix
- src/website/tracker/settings.py
towards #464 and needed for #544
> refactor: structured config for STATIC_ROOT

- src/website/webview/static/style.css
- src/website/webview/templates/components/issue.html
- src/website/webview/templates/components/maintainers_list.html
- src/website/webview/templates/issue_detail.html
- src/website/webview/templates/issue_list.html
- src/website/webview/templatetags/viewutils.py
- src/website/webview/views.py
This addresses #544 by implementing:
- a component for issues (as in `NixpkgsIssue`, which differ from "suggestions" that are listed in the other tabs, and is the reason why there was no view until now)
- a paginated list view of published issues (the landing page of "Published issues")
- a detailed view per issue, each having a URL
<details>
<summary>Screenshots</summary>
</details>
- The `NixpkgsIssue` model and the `CveRecord` model do not carry the same info as suggestions used in other tabs, there is not the same degree of continuity as there is between the other tabs. Still, when publishing an issue from a draft, you can directly browse to the issue link.
- In the list view, the "related derivations" are not passed down to the view. This is a first draft only and I'm open to …
> Implement consistent views for published issues

- contrib/grafana-dashboard.json
This adds the JSON file for a small Grafana dashboard of some metrics mentioned in #345. This is what it looks like: 
The rest of the metrics (host metrics, complete database metrics, etc) makes more sense to be viewed in their respective upstream dashboards.
Closes #345
Closes #222
> Add a Grafana dashboard with stats we care about

- src/website/shared/listeners/cache_issues.py
- src/website/shared/listeners/cache_suggestions.py
- src/website/shared/models/cached.py
- src/website/webview/templates/components/issue.html
#580 has been merged prematurely. This polishes what should have been included in #580.
> Polish update on issue caching for shared package view

- infra/sectracker.nix
Automatically [optimise the nix store](https://wiki.nixos.org/wiki/Storage_optimization#Automatic) by using a timer. We could argue that this should be set in `nix/web-security-tracker.nix`, but I don't want to "force" this on all installations and I think its best to allow admins to make this decision themselves. This reasoning shall be documented in #594.
> infra: Optimise the nix store by default

- src/shared/auth/github_webhook.py
This catches a 500 error when the signature header is missing from the webhook endpoint.
> fix: Catch error when webhook signature is missing

- src/shared/listeners/nix_channels.py
Closes #564. I believe this was the initial intention of this `start_evaluation_jobs_upon_updates` fuction.
> fix: Remove not needed trigger that bugged evals

- .github/workflows/dry-activations.yaml
- CONTRIBUTING.md
Running dry-activate on pull requests has multiple issues:
- As a comment alluded, this is a trusted operation and we shouldn't trust PRs
- It mostly tests the infrastructure config and not the application changes themselves, which could become a blocker if infra was broken.
> fix: Run dry-activate on merges only
